version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: 
          name: install dependencies
          command: |
            # pip install --upgrade setuptools
            sudo apt-get install python3-venv
            python3 -m venv myenv
            . myenv/bin/activate
            pip3 install -r requir
            ements.txt
            
  
      - run:
          name: run tests
          command: |
           . myenv/bin/activate
           tox -- -x --cov=weather
          
            